### PR TITLE
Touch support for `PaneGrid` and `PickList`

### PR DESCRIPTION
**Pull request by discordance**
Hello ! 
I was trying Iced and found the workflow amazing.  With folks we were interested to see how it would play on iOS and, long story short, here is my take porting Simlay’s work on Touch support PR for the new 0.2 API.

Widgets are almost complete, and I can test the easy way thanks to this super cool project:

[cargo-mobile](https://github.com/BrainiumLLC/cargo-mobile)

 I have cool results on devices and simulators with few rough edges.
I have a small crash with font-kit and the system font loading, I worked around by using default fonts for now.

It misses the virtual keyboard management on mobile, but it is out of scope of this PR as it seems to be a **winit** fix as discussed on Zulip’s thread.

Here is how I could make it work in `cargo-mobile` :
   
1 - Installed, then generated a new cargo-mobile project using the winit template.
2 - Ported one of the simplest Iced example in the lib.rs.
3 - Open the project in Xcode with `cargo apple open`.
4 - Added CoreText in the list of Frameworks linked.
5 - Disabled Metal Validation API .

I’m open to give a bit of extra work here if needed!

Cheers!

### CODE REVIEW

**Comment by matthieugayon** [comment]
It works ! I believe **5 - Disabled Metal Validation API ** is related to 

https://github.com/hecrj/iced/issues/511

and 

https://github.com/gfx-rs/wgpu/issues/185

**Comment by discordance** [comment]
dem1

**Comment by matthieugayon** [comment]
I just did a PR on cargo mobile https://github.com/BrainiumLLC/cargo-mobile/pull/4
It's based on the tour example and it's pointing to this branch :)

**Comment by ammen99** [comment]
I have also tested this on my laptop with a touchscreen, works for such devices as well!

**Comment by hecrj** [comment]
Looks promising! Thank you!

Would it be possible to keep the commit history of #57? Maybe we could rebase that branch and then apply these changes on top. It'd be easier to review the changes that way.

**Comment by hecrj** [comment]
I have successfully resolved the conflicts in #57. I'd appreciate any feedback there! It's very likely I missed something.

This PR seems to be adding touch support to the `PaneGrid` and `PickList` so it would be great to rebase the changes here on top of that branch.

**Comment by discordance** [comment]
Ok got it, makes total sense, I will look into rebasing this PR on top of #57

**Comment by cryptoquick** [comment]
I'm so excited to see this work! I was tempted to investigate, also. Once this is merged in, what else would be needed to get, say, the todo list example building for mobile?

**Review by hecrj — APPROVED** [review]
Thanks a lot for rebasing! :tada: 

I have changed a bunch of minor details but everything looks good! I think we can finally merge this :partying_face:

**Pull request merged**
