### PR TITLE
add window visibility

### LINKED ISSUE #824: Add visible window setting
Would be great to set initial visibility of window with a new window setting that gets passed to https://docs.rs/winit/0.24.0/winit/window/struct.WindowBuilder.html#method.with_visible.

Related to #822 and implementing a sys tray for our application. We want to have the option to launch it to the tray. We have a workaround but we get a very brief "flash" of the iced window before it gets hidden.

### PR DESCRIPTION
**Pull request by tarkah**
resolves #824

### CODE REVIEW

**Review by hecrj — COMMENTED** [review]
I wonder if this could be a new variant in `window::Mode` instead?

**Comment by tarkah** [comment]
I had the same thought as well, but I went with this implementation as it's more 1:1 with winit.

Let me push a new commit with that change and see if you prefer it that way.

**Comment by tarkah** [comment]
@hecrj Yeah, I think `Mode::Hidden` is cleaner. A simpler implementation and we don't have to add a new Application method.

**Review by hecrj — APPROVED** [review]
Agreed. Looks great!

Thank you 🎉

**Pull request merged**
