### PR TITLE
Quit application when `Cmd+Q` is pressed on macOS

### PR DESCRIPTION
**Pull request by hecrj**
This is a nice default until we tackle #114.

### CODE REVIEW

**Comment by cryptoquick** [comment]
Sweet! Just tested it also, works great, and I'm very glad to see this minor UX improvement.

**Comment by GyulyVGC** [comment]
It's nice to have this shortcut by default on macOS, but what if I'd like to override its behaviour?
I tried setting up a subscription to capture the COMMAND+Q shortcut... it works on Windows/Linux but not on macOS.
In my opinion, `cmd+Q` should trigger a CloseRequested Event, so that a user can intercept it and perform additional operations before invoking `window::close()`.

**Comment by hecrj** [comment]
@GyulyVGC  See https://docs.rs/iced/latest/iced/settings/struct.Settings.html#structfield.exit_on_close_request.

**Comment by GyulyVGC** [comment]
Yeah, I noticed it and set it to false, the 'x' button of the window works as expected triggering the actions I defined, but the Cmd+Q shortcut closes the app immediately even in this case... will check better

**Comment by tarkah** [comment]
Can confirm that Cmd+Q doesn't send a CloseRequested event and still force closes the app even with the exit on close requested set to false.

**Comment by hecrj** [comment]
That's strange. We are only breaking here:

https://github.com/iced-rs/iced/blob/a057f8811bfc47afc4271f05b92263a19122d888/winit/src/application.rs#L411-L413

And here:

https://github.com/iced-rs/iced/blob/a057f8811bfc47afc4271f05b92263a19122d888/winit/src/application.rs#L565-L569

Maybe it's `winit` stopping the event loop?

**Comment by GyulyVGC** [comment]
I take advantage of this moment to also point out that Ctrl+C on terminal doesn't trigger the event, and this could lead to unexpected behaviors if developers don't know it

**Comment by GyulyVGC** [comment]
It's even weirder considering that `Cmd+Q` keeps closing the app even if those lines are commented out:
https://github.com/iced-rs/iced/blob/master/winit/src/application.rs#L599-L608

**Pull request merged**
