### PR TITLE
wgpu: Update to 0.10

### LINKED ISSUE #933: WGPU 0.9 breaks Image rendering [AMD Integrated]
grafik

Confirmed that since commit c70f90f3206f7f5176831b7896d8acc147dd2c53 this behaviour occurs and beforehand everything works as expected. Don't know if this is wgpu or iced related.

## System

OS: Windows 10
CPU: Ryzen 5 4500U
GPU: Radeon Graphics (Integrated)

## Logs
[logs.txt](https://github.com/hecrj/iced/files/6721363/logs.txt)

## Fix

Fixed by #1000

### PR DESCRIPTION
**Pull request by PolyMeilex**
- ~~blocked by: https://github.com/hecrj/wgpu_glyph/pull/73~~ (no longer blocking)
- Opengl backedn of wgpu now works as expected in iced (I never managed to run it in prev versions, but now it works)
  - EDIT: nope, never mind, on my second device it does not work at all, so it's still unstable (at least on linux)
- Images in OpenGL are for some reason black, I will investigate this a little bit more soon.
- Wgpu SwapChain not longer exists, so surface was added as an argument to draw() in compositor trait, ~~wgpu implementation of compositors uses `()` as a SwapChain type now.~~

Fixes #933.

### CODE REVIEW

**Comment by kvark** [comment]
Please file issues about OpenGL backend!

**Comment by PolyMeilex** [comment]
- https://github.com/gfx-rs/naga/pull/1265 Is now blocking this PR

**Review by hecrj — APPROVED** [review]
Thank you @PolyMeilex! :tada: 

I think this is ready to merge!

**Comment by PolyMeilex** [comment]
After update of deps (maybe new naga?), text is no longer rendered in OpenGL backend... I'm kinda tired of debugging OpenGL backend, if I'll find some free time I will try to find a reason for this and report it (probably upstream)

**Pull request merged**
