### PR TITLE
feat(web): Support in-memory image data

### PR DESCRIPTION
**Pull request by Liamolucko**
I had to create two methods which basically do the same thing, `from_memory` and `from_slice`, because `from_memory` takes ownership of the bytes to be compatible with `iced_native`.

Also, `Data` is incompatible, because if I stored the bytes in `Data` and created a new object URL every render, it would have caused a memory leak because bumpalo doesn't call destructors and there'd be no way to call URL.revokeObjectUrl on it. It's also more efficient this way.

### CODE REVIEW

**Comment by Liamolucko** [comment]
Whoops, this isn't actually working - I think when I was testing if the mime type needed to be specified it must have still been in browser cache or something.

**Comment by Liamolucko** [comment]
I didn't realise widgets were dropped immediately after being constructed, which meant that the image handle was being dropped and the object url invalidated. So I've changed `Data` to work the same as in `iced_native`, and create the object url when rendering, which means this now works but causes a memory leak every time an image is rendered :/.

I'm not sure how this can be done without causing a memory leak.

**Review by hecrj — COMMENTED** [review]
We could force users to keep the `Handle` in their `Application` state and clone it when creating the `Image` widget, instead of creating the `Handle` every time while rendering.

**Review by hecrj — APPROVED** [review]
We can merge this for now and improve the API / performance in another PR.

Thank you! 🙇

**Pull request merged**
