### PR TITLE
update to winit 0.23 api

### PR DESCRIPTION
**Pull request by aentity**
WIP will change to winit 0.23 once crates.io is released

### CODE REVIEW

**Comment by aentity** [comment]
Ready for review

**Comment by aentity** [comment]
@hecrj I think this is ready

**Comment by kaimast** [comment]
I just tested your branch it works flawlessly for me :) 

It would be great if this could be merged quickly. Winit 0.23 fixes a large number of Wayland bugs among other improvements.

**Comment by VitalyAnkh** [comment]
I'm experiencing a compile error about wayland... 
```
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting
```
Looking forwad to this.

**Review by hecrj — APPROVED** [review]
Looks good! :+1: 

I have changed the `KeyCode` in 16cd38a198f8bd94c8957eee9165dde4e8f85c68 to keep the names and `repr` consistent with `winit` for now.

**Pull request merged**
