### PR TITLE
Upgrade wgpu

### LINKED ISSUE #511: metal validation crash on macos
Using: ff15ebc54778dee2a7262469c8a2bcd5abecd4d1 (current master, wgpu 0.6)

Error:
```
validateFunctionArguments:3478: failed assertion `Vertex Function(main0): argument _17[0] from buffer(0) with offset(0) and length(68) has space for 68 bytes, but argument has a length(80).'
```
Backtrace (release, sorry):
```
thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff683a92c6 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x000000010167f80d libsystem_pthread.dylib`pthread_kill + 284
    frame #2: 0x00007fff683136a6 libsystem_c.dylib`abort + 127
    frame #3: 0x00007fff682dc20d libsystem_c.dylib`__assert_rtn + 324
    frame #4: 0x00007fff409886b6 Metal`MTLReportFailure + 567
    frame #5: 0x00007fff5ab1719b MetalTools`validateFunctionArguments(id<MTLDevice>, NSString*, NSString, NSArray*, MTLDebugFunctionArgument*, unsigned long, MTLDebugFunctionArgument, unsigned long, MTLDebugFunctionArgument, unsigned long) + 1019
    frame #6: 0x00007fff5ab16854 MetalTools`-[MTLDebugRenderCommandEncoder validateCommonDrawErrors:instanceCount:baseInstance:maxVertexID:] + 805
    frame #7: 0x00007fff5ab17fe2 MetalTools`-[MTLDebugRenderCommandEncoder validateDrawIndexedPrimitives:indexCount:indexType:indexBuffer:indexBufferOffset:instanceCount:function:] + 187
    frame #8: 0x00007fff5ab183af MetalTools`-[MTLDebugRenderCommandEncoder drawIndexedPrimitives:indexCount:indexType:indexBuffer:indexBufferOffset:] + 133
    frame #9: 0x0000000100053711 _foo`gfx_backend_metal::command::exec_render::h123d51eaa38d7465(encoder=0x0000000102964200, command=<unavailable>, resources=<unavailable>) + 2497 [opt]
    frame #10: 0x000000010005d1f2 _foo`_$LT$gfx_backend_metal..command..CommandBuffer$u20$as$u20$gfx_hal..command..CommandBuffer$LT$gfx_backend_metal..Backend$GT$$GT$::draw_indexed::hcd6421e98acd2ef3(self=<unavailable>, indices=<unavailable>, base_vertex=<unavailable>, instances=<unavailable>) + 210 [opt]
    frame #11: 0x00000001006dee5b _foo`wgpu_core::command::render::_$LT$impl$u20$wgpu_core..hub..Global$LT$G$GT$$GT$::command_encoder_run_render_pass_impl::h4fb173dda8bd6f8d(self=<unavailable>, encoder_id=<unavailable>, base=<unavailable>, color_attachments=<unavailable>, depth_stencil_attachment=<unavailable>) + 43851 [opt]
    frame #12: 0x000000010070ddad _foo`_$LT$wgpu..RenderPass$u20$as$u20$core..ops..drop..Drop$GT$::drop::hf0bc6f2fdaf89448(self=<unavailable>) + 157 [opt]
    frame #13: 0x00000001000d11d8 _foo`iced_wgpu::backend::Backend::flush::h274c2929d22fb18e(self=<unavailable>, device=<unavailable>, scale_factor=<unavailable>, transformation=<unavailable>, layer=<unavailable>, staging_belt=<unavailable>, encoder=<unavailable>, target=<unavailable>, target_width=<unavailable>, target_height=<unavailable>) + 1080 [opt]
```

Is uniform iced uses aligned ok?

### PR DESCRIPTION
**Pull request by Dispersia**
Draft PR to upgrade wgpu and use wgsl so cross can stop being compiled for android, includes temporary patches until fix for staging belt goes out.

Fixes #511.
Closes #523.

### CODE REVIEW

**Review by hecrj — COMMENTED** [review]
I got this to compile using the latest releases of `wgpu` and `wgpu_glyph`.

However, I am getting some shader validation errors once I try to run the `tour`.

**Comment by Dispersia** [comment]
let me take a look, thanks for the patch so hopefully not too bad to fix

**Comment by Dispersia** [comment]
talked to wgpu team and had me make an issue: https://github.com/gfx-rs/naga/issues/882 will be waiting on that. I was suggested to just pad it up to the size it wants, but if i do that the uniform size doesn't match, and then if i pad the actual byte array it gives the original error again, so going to look into it further. Seems to be something introduced in 0.8.1

**Comment by Dispersia** [comment]
As was mentioned in that issue, the error wasn't super helpful but structs in uniforms need to align to their largest member, in this case mat4x4<f32> which aligns to 16: https://gpuweb.github.io/gpuweb/wgsl/#alignment-and-size

**Comment by hecrj** [comment]
Thanks for fixing that @Dispersia! 🎉 I believe this should probably fix #511 too.

However, I still get a panic caused by a validation error on macOS Catalina:

```
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `iced_wgpu::quad pipeline`
    Internal error in VERTEX shader: Error compiling the shader "\"Compilation failed: \\n\\nprogram_source:106:17: error: declaration with attribute \\\'position\\\' already specified\\n, metal::float4 coord [[position]]\\n  ~~~~~~~~~~~~~~^~~~~\\nprogram_source:105:17: note: previous declaration with attribute \\\'position\\\' here\\n, metal::float4 position [[position]]\\n                ^\\n\""
```

**Comment by kaimast** [comment]
I just tested your branch on Linux/X11. The wgpu integration example works fine but the solar system one crashes on startup.

```
~/dev/tmp/iced upgrade-wgpu ❯ env RUST_BACKTRACE=full cargo run --package solar_system                                                                                                    ✘ SEGV  48s
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/solar_system`
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

wgpu error: Validation Error

Caused by:
    In Device::create_bind_group
      note: label = `iced_wgpu::triangle::msaa uniforms bind group`
    sampler binding 0 expects filtering = false, but given a sampler with filtering = true


thread 'main' panicked at 'Handling wgpu errors as fatal by default', /home/kai/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.8.1/src/backend/direct.rs:1955:5
stack backtrace:
   0:     0x55ff96e89910 - std::backtrace_rs::backtrace::libunwind::trace::hdcf4f90f85129e83
                               at /rustc/5c029265465301fe9cb3960ce2a5da6c99b8dcf2/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55ff96e89910 - std::backtrace_rs::backtrace::trace_unsynchronized::h2669e30cb82f6732
                               at /rustc/5c029265465301fe9cb3960ce2a5da6c99b8dcf2/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55ff96e89910 - std::sys_common::backtrace::_print_fmt::hfbda19e17f6db318
                               at /rustc/5c029265465301fe9cb3960ce2a5da6c99b8dcf2/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55ff96e89910 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1a8751bf59281272
                               at /rustc/5c029265465301fe9cb3960ce2a5da6c99b8dcf2/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55ff96eace2f - core::fmt::write::h7aa6cd0067dca82a
                               at /rustc/5c029265465301fe9cb3960ce2a5da6c99b8dcf2/library/core/src/fmt/mod.rs:1094:17
   5:     0x55ff96e85215 - std::io::Write::write_fmt::hd7dd3a1df9b6befb
                               at /rustc/5c029265465301fe9cb3960ce2a5da6c99b8dcf2/library/std/src/io/mod.rs:1584:15
   6:     0x55ff96e8ba1b - std::sys_common::backtrace::_print::h551e9ec8a9fa8106
                               at /rustc/5c029265465301fe9cb3960ce2a5da6c99b8dcf2/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55ff96e8ba1b - std::sys_common::backtrace::print::ha4b1c5e95fa040b3
                               at /rustc/5c029265465301fe9cb3960ce2a5da6c99b8dcf2/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55ff96e8ba1b - std::panicking::default_hook::{{closure}}::h0b34c9ab7fb9f857
                               at /rustc/5c029265465301fe9cb3960ce2a5da6c99b8dcf2/library/std/src/panicking.rs:208:50
   9:     0x55ff96e8b4fd - std::panicking::default_hook::h3067e8318decd17a
                               at /rustc/5c029265465301fe9cb3960ce2a5da6c99b8dcf2/library/std/src/panicking.rs:225:9
  10:     0x55ff96e8bfcd - std::panicking::rust_panic_with_hook::h81b8facc50f34daa
                               at /rustc/5c029265465301fe9cb3960ce2a5da6c99b8dcf2/library/std/src/panicking.rs:591:17
  11:     0x55ff964620d3 - std::panicking::begin_panic::{{closure}}::h321d8656493a5d60
                               at /home/kai/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:520:9
  12:     0x55ff964675f9 - std::sys_common::backtrace::__rust_end_short_backtrace::hc25627b7e193d4b7
                               at /home/kai/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55ff96462009 - std::panicking::begin_panic::h4c8176da4b4ced29
                               at /home/kai/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
  14:     0x55ff95e91cec - wgpu::backend::direct::default_error_handler::hc8c00d5eac853cc2
                               at /home/kai/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.8.1/src/backend/direct.rs:1955:5
  15:     0x55ff95db4b9c - core::ops::function::Fn::call::h34ea71e30a2804b6
                               at /home/kai/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
  16:     0x55ff95ddb8e2 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h09bd3d9b27d73596
                               at /home/kai/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1589:9
  17:     0x55ff95e91be1 - wgpu::backend::direct::ErrorSinkRaw::handle_error::h45e9772f94dc527c
                               at /home/kai/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.8.1/src/backend/direct.rs:1942:9
  18:     0x55ff95e85041 - wgpu::backend::direct::Context::handle_error::h50ddd10a85e06df5
                               at /home/kai/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.8.1/src/backend/direct.rs:93:9
  19:     0x55ff95e8bded - <wgpu::backend::direct::Context as wgpu::Context>::device_create_bind_group::hfd81f9a80093d338
                               at /home/kai/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.8.1/src/backend/direct.rs:938:13
  20:     0x55ff96064727 - wgpu::Device::create_bind_group::h02f63f4d3e860868
                               at /home/kai/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.8.1/src/lib.rs:1571:17
  21:     0x55ff95c3c178 - iced_wgpu::triangle::msaa::Blit::new::h6701d55dc97e3afd
                               at /home/kai/dev/tmp/iced/wgpu/src/triangle/msaa.rs:44:13
  22:     0x55ff95be3189 - iced_wgpu::triangle::Pipeline::new::{{closure}}::h1bcd634956b74d1d
                               at /home/kai/dev/tmp/iced/wgpu/src/triangle.rs:206:40
  23:     0x55ff95bdc528 - core::option::Option<T>::map::h2ae83fcd3493eb27
                               at /home/kai/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:487:29
  24:     0x55ff95c4dcde - iced_wgpu::triangle::Pipeline::new::h61ef4c793b378576
                               at /home/kai/dev/tmp/iced/wgpu/src/triangle.rs:206:19
  25:     0x55ff95c3e2fa - iced_wgpu::backend::Backend::new::hd1c028397630a962
                               at /home/kai/dev/tmp/iced/wgpu/src/backend.rs:37:33
  26:     0x55ff95c29a19 - iced_wgpu::window::compositor::Compositor::create_backend::h80365374c72c668d
                               at /home/kai/dev/tmp/iced/wgpu/src/window/compositor.rs:77:9
  27:     0x55ff95ac66b8 - <iced_wgpu::window::compositor::Compositor as iced_graphics::window::compositor::Compositor>::new::h2b7333615a06b36f
                               at /home/kai/dev/tmp/iced/wgpu/src/window/compositor.rs:97:23
  28:     0x55ff95b926e5 - iced_winit::application::run::h7e3e96481d560caf
                               at /home/kai/dev/tmp/iced/winit/src/application.rs:151:34
  29:     0x55ff95b6b36b - iced::application::Application::run::hda86147dacd7badc
                               at /home/kai/dev/tmp/iced/src/application.rs:219:16
  30:     0x55ff95b14277 - solar_system::main::h316013c452806dd8
                               at /home/kai/dev/tmp/iced/examples/solar_system/src/main.rs:18:5
  31:     0x55ff95b4e512 - core::ops::function::FnOnce::call_once::h9ea1938231e87869
                               at /home/kai/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  32:     0x55ff95ab220a - std::sys_common::backtrace::__rust_begin_short_backtrace::h3f9f1432cd692bd1
                               at /home/kai/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  33:     0x55ff95b3a096 - std::rt::lang_start::{{closure}}::h737492ca953cccca
                               at /home/kai/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:49:18
  34:     0x55ff96e8c3ca - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h3b8c329143d7638a
                               at /rustc/5c029265465301fe9cb3960ce2a5da6c99b8dcf2/library/core/src/ops/function.rs:259:13
  35:     0x55ff96e8c3ca - std::panicking::try::do_call::h4b72c261b4eefc1b
                               at /rustc/5c029265465301fe9cb3960ce2a5da6c99b8dcf2/library/std/src/panicking.rs:379:40
  36:     0x55ff96e8c3ca - std::panicking::try::h703d31b7896cbd49
                               at /rustc/5c029265465301fe9cb3960ce2a5da6c99b8dcf2/library/std/src/panicking.rs:343:19
  37:     0x55ff96e8c3ca - std::panic::catch_unwind::h37cad9b35388a915
                               at /rustc/5c029265465301fe9cb3960ce2a5da6c99b8dcf2/library/std/src/panic.rs:431:14
  38:     0x55ff96e8c3ca - std::rt::lang_start_internal::hab5a8a909af4f90e
                               at /rustc/5c029265465301fe9cb3960ce2a5da6c99b8dcf2/library/std/src/rt.rs:34:21
  39:     0x55ff95b3a070 - std::rt::lang_start::ha2345f6196cfc1ee
                               at /home/kai/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:48:5
  40:     0x55ff95b148ac - main
  41:     0x7fb6ce547565 - __libc_start_main
  42:     0x55ff95aaee9e - _start
  43:                0x0 - <unknown>
fish: “env RUST_BACKTRACE=full cargo r…” terminated by signal SIGSEGV (Address boundary error)
```

**Comment by Dispersia** [comment]
interesting, that was passing before 0.8 release but i guess new validation broke it, which is good! However, looking into that pipeline, there's actually several things im having a hard time understanding what it's doing, the main thing is the uniform, it's a dynamically sized transform, but isn't defined as an array in the shader. I'm not sure how glsl is even handling that currently, but once i figure out the intent I'll try to get a fix for that. Thanks for testing it!

**Comment by hecrj** [comment]
I have reverted 2d549d806cd9ff1d7b7b237d818cd24c84957c83, as removing the padding in `triangle` was causing this error:

```
wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `iced_wgpu encoder`
    In a set_bind_group command
      note: bind group = `iced_wgpu::triangle uniforms bind group`
    dynamic binding at index 0: offset 64 does not respect `BIND_BUFFER_ALIGNMENT`
```

I think I have also fixed the issue reported by @kaimast in 4cbc34524598756ce18cb25a664bc6f256d42851. Let me know!

All the examples seem to work on my end now.

**Comment by Dispersia** [comment]
ha, you would think it would be obvious that i removed padding and then had alignment issues, but oh well haha. Thanks for the patch, tested on x11 and windows and all examples seem good to me too

**Review by hecrj — APPROVED** [review]
Thanks again everyone! I think we can merge this 🎉

**Pull request merged**
