### PR TITLE
wgpu: add vec3 padding in quad.vert; fixes #511

### LINKED ISSUE #511: metal validation crash on macos
Using: ff15ebc54778dee2a7262469c8a2bcd5abecd4d1 (current master, wgpu 0.6)

Error:
```
validateFunctionArguments:3478: failed assertion `Vertex Function(main0): argument _17[0] from buffer(0) with offset(0) and length(68) has space for 68 bytes, but argument has a length(80).'
```
Backtrace (release, sorry):
```
thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff683a92c6 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x000000010167f80d libsystem_pthread.dylib`pthread_kill + 284
    frame #2: 0x00007fff683136a6 libsystem_c.dylib`abort + 127
    frame #3: 0x00007fff682dc20d libsystem_c.dylib`__assert_rtn + 324
    frame #4: 0x00007fff409886b6 Metal`MTLReportFailure + 567
    frame #5: 0x00007fff5ab1719b MetalTools`validateFunctionArguments(id<MTLDevice>, NSString*, NSString, NSArray*, MTLDebugFunctionArgument*, unsigned long, MTLDebugFunctionArgument, unsigned long, MTLDebugFunctionArgument, unsigned long) + 1019
    frame #6: 0x00007fff5ab16854 MetalTools`-[MTLDebugRenderCommandEncoder validateCommonDrawErrors:instanceCount:baseInstance:maxVertexID:] + 805
    frame #7: 0x00007fff5ab17fe2 MetalTools`-[MTLDebugRenderCommandEncoder validateDrawIndexedPrimitives:indexCount:indexType:indexBuffer:indexBufferOffset:instanceCount:function:] + 187
    frame #8: 0x00007fff5ab183af MetalTools`-[MTLDebugRenderCommandEncoder drawIndexedPrimitives:indexCount:indexType:indexBuffer:indexBufferOffset:] + 133
    frame #9: 0x0000000100053711 _foo`gfx_backend_metal::command::exec_render::h123d51eaa38d7465(encoder=0x0000000102964200, command=<unavailable>, resources=<unavailable>) + 2497 [opt]
    frame #10: 0x000000010005d1f2 _foo`_$LT$gfx_backend_metal..command..CommandBuffer$u20$as$u20$gfx_hal..command..CommandBuffer$LT$gfx_backend_metal..Backend$GT$$GT$::draw_indexed::hcd6421e98acd2ef3(self=<unavailable>, indices=<unavailable>, base_vertex=<unavailable>, instances=<unavailable>) + 210 [opt]
    frame #11: 0x00000001006dee5b _foo`wgpu_core::command::render::_$LT$impl$u20$wgpu_core..hub..Global$LT$G$GT$$GT$::command_encoder_run_render_pass_impl::h4fb173dda8bd6f8d(self=<unavailable>, encoder_id=<unavailable>, base=<unavailable>, color_attachments=<unavailable>, depth_stencil_attachment=<unavailable>) + 43851 [opt]
    frame #12: 0x000000010070ddad _foo`_$LT$wgpu..RenderPass$u20$as$u20$core..ops..drop..Drop$GT$::drop::hf0bc6f2fdaf89448(self=<unavailable>) + 157 [opt]
    frame #13: 0x00000001000d11d8 _foo`iced_wgpu::backend::Backend::flush::h274c2929d22fb18e(self=<unavailable>, device=<unavailable>, scale_factor=<unavailable>, transformation=<unavailable>, layer=<unavailable>, staging_belt=<unavailable>, encoder=<unavailable>, target=<unavailable>, target_width=<unavailable>, target_height=<unavailable>) + 1080 [opt]
```

Is uniform iced uses aligned ok?

### PR DESCRIPTION
**Pull request by aentity**
This adds a vec4 in place of single float in quad uniforms to avoid metal validation errors.

### CODE REVIEW

**Comment by aentity** [comment]
@hecrj forgot to make PR, can review please?

**Comment by aentity** [comment]
@hecrj ping

**Comment by hecrj** [comment]
Hey, thanks!

What is exactly the cause of this issue? Could it be a bug in [`wgpu`](https://github.com/gfx-rs/wgpu-rs)?

**Comment by aentity** [comment]
Wgpu should catch yes, but issue is (i think) the uniform is not correctly aligned / padded according to metal layout requirements. It could perhaps be shaderc bug, which doesn't add the necessary padding at end of the uniform, I'm not sure?

**Comment by hecrj** [comment]
I see. I believe that, before merging, we need to identify the root cause of the issue and whether it is up to us to fix it.

The proposed fix here affects all of our `wgpu` backends, not only Metal.

**Comment by hecrj** [comment]
Is this issue still present after #725? If it is, does `wgpu` provide any more hints about what is going on?

I am closing this, but feel free to reopen it if you find out the actual cause.

**Pull request closed without merging**
