### PR TITLE
Add performance-test for UserInterface::build with Criterion

### PR DESCRIPTION
**Pull request by TGotwig**
Relates #7
Runnable by `cargo bench`

### CODE REVIEW

**Comment by TGotwig** [comment]
No problem, probably can look at the weekend or so 😊

**Comment by erlend-sh** [comment]
Could this be merged as-is for a start?

**Comment by hecrj** [comment]
@erlend-sh I will definitely merge this once we start working on benchmarks.

For now, the API is currently changing and we don't want to maintain an empty benchmark.

**Comment by TGotwig** [comment]
Oh the API has changed a lot already 🙀
I'll close this and maybe give it another try after this month or so 🐱

**Pull request closed without merging**
