### PR TITLE
update resvg to latest, same with guillotiere

### PR DESCRIPTION
**Pull request by aentity**
Hello, also to update resvg, which removes old deflate and old png, and many other deps in a tree.

### CODE REVIEW

**Comment by aentity** [comment]
Oh no, it looks that resvg has removed raqote and uses a "tiny skia" which is native build? maybe it's not good, i don't know.

**Comment by hecrj** [comment]
Yeah, the dependencies of `resvg` have grown considerably. We may consider using an updated version once [`tiny-skia`] matures or whenever we implement a Skia renderer.

In any case, thanks for taking a shot at this. Closing for now!

[`tiny-skia`]: https://github.com/RazrFalcon/tiny-skia

**Comment by myfreeweb** [comment]
Switched to resvg from git in my fork now: https://github.com/myfreeweb/iced/commit/a2d07cb759d6ac3debc04ae6d0c906672cfa712b (tiny-skia is all-Rust already)

It outputs RGBA instead of BGRA.. for now I just added the conversion right there using `image`, but it would be much better to "convert" in the fragment shader.

Code size of rustybuzz+tiny_skia+usvg+resvg in release mode is considerable, though wgpu+wgpu_core+naga+gfx_backend_vulkan+ash is still bigger :)

```
 File  .text     Size Crate
 9.4%  22.7% 812.1KiB wgpu
 3.9%   9.4% 337.4KiB std
 3.1%   7.4% 266.0KiB rustybuzz
 3.0%   7.3% 260.9KiB tiny_skia
 2.2%   5.3% 189.0KiB usvg
 2.1%   5.0% 179.4KiB iced_wgpu
 1.9%   4.6% 166.1KiB naga
 1.7%   4.0% 144.3KiB wgpu_core
 1.3%   3.1% 111.8KiB smithay_client_toolkit
 1.0%   2.5%  90.9KiB resvg
 0.9%   2.3%  82.1KiB ttf_parser
 0.9%   2.1%  75.0KiB wayland_client
 0.7%   1.8%  63.1KiB gfx_backend_vulkan
```

**Comment by hecrj** [comment]
@myfreeweb Cool! Yeah, I saw the announcement of `tiny-skia` a while ago.

We are just waiting for a new `resvg` release at this point. Feel free to open a PR!

**Pull request closed without merging**
